//! Matrix OAuth QR account acquisition (ADR 0097).
//!
//! HTTP clients poll an in-memory flow resource while this engine owns the
//! matrix-rust-sdk login future. Only a non-secret filesystem breadcrumb is
//! durable; QR payloads, check codes, OAuth user codes, tokens, and rendezvous
//! URLs never enter Postgres or logs.

use std::{
    collections::HashMap,
    future::IntoFuture,
    sync::{Arc, Mutex},
    time::{Duration, Instant},
};

use axon_core::SyncConfig;
use axon_store::Store;
use futures_util::{Stream, StreamExt};
use matrix_sdk::{
    authentication::oauth::qrcode::{
        CheckCodeSender, DeviceAuthorizationOAuthError, GeneratedQrProgress, LoginProgress,
        Msc4108IntentData, QRCodeLoginError, QrCodeData, QrCodeIntent, QrCodeIntentData,
        QrProgress, SecureChannelError,
    },
    ruma::{OwnedServerName, OwnedUserId},
    Client,
};
use tokio::sync::{oneshot, OwnedSemaphorePermit, Semaphore};
use tokio_util::{sync::CancellationToken, task::TaskTracker};
use tracing::Instrument;
use uuid::Uuid;

use crate::{
    client::{
        build_matrix_oauth_acquire_client, remove_matrix_oauth_acquire_staging,
        MatrixOAuthAcquireClientError,
    },
    error::SyncError,
    lifecycle::{AccountLifecycle, LifecycleError},
    MatrixOAuthRegistrationManager,
};

const MAX_CONCURRENT_FLOWS: usize = 8;
const MAX_RETAINED_FLOWS: usize = 256;
const MAX_QR_BASE64_BYTES: usize = 8 * 1024;
const MAX_USER_ID_BYTES: usize = 1024;
const FLOW_TTL: Duration = Duration::from_secs(10 * 60);
const TERMINAL_RETENTION: Duration = Duration::from_secs(2 * 60);
const REAPER_INTERVAL: Duration = Duration::from_secs(5);
const WHOAMI_TIMEOUT: Duration = Duration::from_secs(15);
const REVOCATION_TIMEOUT: Duration = Duration::from_secs(10);

/// A progress stream that becomes permanently pending after its first close.
///
/// Matrix SDK progress and completion are separate channels. The completion
/// future may still be running when progress closes, so returning `None` again
/// would leave an always-ready branch in `tokio::select!` and busy-spin until
/// completion, cancellation, or timeout.
struct ProgressUntilClosed<S> {
    inner: S,
    closed: bool,
}

impl<S> ProgressUntilClosed<S>
where
    S: Stream + Unpin,
{
    fn new(inner: S) -> Self {
        Self {
            inner,
            closed: false,
        }
    }

    async fn next(&mut self) -> Option<S::Item> {
        if self.closed {
            return std::future::pending().await;
        }
        let next = self.inner.next().await;
        if next.is_none() {
            self.closed = true;
        }
        next
    }
}

/// Which device presents the QR image.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MatrixOAuthAcquirePresentation {
    /// Axon generates QR data for the existing trusted device to scan.
    Display,
    /// An Axon client scans QR data generated by the existing trusted device.
    Scan,
}

impl MatrixOAuthAcquirePresentation {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Display => "display",
            Self::Scan => "scan",
        }
    }
}

/// Stable Axon stage names; SDK enum names never cross `/v1/`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MatrixOAuthAcquireStage {
    Starting,
    QrReady,
    CheckCodeToDisplay,
    CheckCodeRequired,
    WaitingForAuthorization,
    SyncingSecrets,
    Done,
    Failed,
    Cancelled,
}

impl MatrixOAuthAcquireStage {
    fn is_terminal(self) -> bool {
        matches!(self, Self::Done | Self::Failed | Self::Cancelled)
    }
}

/// A presentation-safe point-in-time flow view.
#[derive(Clone, PartialEq, Eq)]
pub struct MatrixOAuthAcquireState {
    pub flow_id: Uuid,
    pub expected_user_id: String,
    pub presentation: MatrixOAuthAcquirePresentation,
    pub stage: MatrixOAuthAcquireStage,
    pub qr_code_data: Option<String>,
    pub check_code: Option<String>,
    pub authorization_user_code: Option<String>,
    pub verification_uri: Option<String>,
    pub account_id: Option<Uuid>,
    pub error_code: Option<String>,
}

impl MatrixOAuthAcquireState {
    fn new(
        flow_id: Uuid,
        expected_user_id: String,
        presentation: MatrixOAuthAcquirePresentation,
    ) -> Self {
        Self {
            flow_id,
            expected_user_id,
            presentation,
            stage: MatrixOAuthAcquireStage::Starting,
            qr_code_data: None,
            check_code: None,
            authorization_user_code: None,
            verification_uri: None,
            account_id: None,
            error_code: None,
        }
    }

    fn set_stage(&mut self, stage: MatrixOAuthAcquireStage) {
        self.stage = stage;
        self.qr_code_data = None;
        self.check_code = None;
        self.authorization_user_code = None;
        self.verification_uri = None;
        self.account_id = None;
        self.error_code = None;
    }
}

/// HTTP-neutral operation errors for the composition-root adapter.
#[derive(Debug, thiserror::Error)]
pub enum MatrixOAuthAcquireError {
    #[error("invalid Matrix user ID")]
    InvalidUserId,
    #[error("too many Matrix OAuth QR login flows are active or retained")]
    Capacity,
    #[error("the Matrix account is already active")]
    AccountAlreadyActive,
    #[error("the Matrix account is being deleted")]
    AccountBeingDeleted,
    #[error("the Matrix account's previous session is still shutting down")]
    AccountDraining,
    #[error("a Matrix OAuth QR login is already in progress for this user")]
    FlowAlreadyExists,
    #[error("Matrix OAuth QR login flow not found: {0}")]
    NotFound(Uuid),
    #[error("input does not match the flow presentation or stage")]
    WrongStage,
    #[error("invalid QR login input: {0}")]
    InvalidInput(&'static str),
    #[error("Matrix OAuth QR login storage failed")]
    Internal,
}

fn create_lifecycle_error(error: LifecycleError) -> MatrixOAuthAcquireError {
    match error {
        LifecycleError::AlreadyActive(_) => MatrixOAuthAcquireError::AccountAlreadyActive,
        LifecycleError::BeingDeleted(_) => MatrixOAuthAcquireError::AccountBeingDeleted,
        LifecycleError::Draining(_) => MatrixOAuthAcquireError::AccountDraining,
        LifecycleError::LoginFinalizing(_) => MatrixOAuthAcquireError::FlowAlreadyExists,
        LifecycleError::InvalidUserId(_) => MatrixOAuthAcquireError::InvalidUserId,
        other => {
            tracing::error!(
                error_class = lifecycle_failure_code(&other),
                "reserving Matrix OAuth QR login identity failed"
            );
            MatrixOAuthAcquireError::Internal
        }
    }
}

struct FlowMutable {
    state: MatrixOAuthAcquireState,
    terminal_at: Option<Instant>,
    scan_tx: Option<oneshot::Sender<QrCodeData>>,
    check_code_tx: Option<oneshot::Sender<u8>>,
    /// Once the successful driver claims finalization, cancellation no longer
    /// competes with the crash-safe database/filesystem commit sequence.
    finalizing: bool,
    /// Released at the first terminal transition while the snapshot remains in
    /// the registry for its retention window.
    permit: Option<OwnedSemaphorePermit>,
}

struct Flow {
    mutable: Mutex<FlowMutable>,
    cancel: CancellationToken,
    staging_dir_name: String,
}

impl Flow {
    fn snapshot(&self) -> MatrixOAuthAcquireState {
        self.mutable
            .lock()
            .expect("Matrix OAuth acquire flow poisoned")
            .state
            .clone()
    }

    fn update(&self, update: impl FnOnce(&mut MatrixOAuthAcquireState)) {
        let mut mutable = self
            .mutable
            .lock()
            .expect("Matrix OAuth acquire flow poisoned");
        if !mutable.state.stage.is_terminal() {
            update(&mut mutable.state);
        }
    }

    fn claim_finalization(&self) -> bool {
        let mut mutable = self
            .mutable
            .lock()
            .expect("Matrix OAuth acquire flow poisoned");
        if mutable.state.stage.is_terminal() || mutable.finalizing {
            return false;
        }
        mutable.finalizing = true;
        true
    }

    fn terminal(
        &self,
        stage: MatrixOAuthAcquireStage,
        account_id: Option<Uuid>,
        error_code: Option<&'static str>,
    ) {
        let mut mutable = self
            .mutable
            .lock()
            .expect("Matrix OAuth acquire flow poisoned");
        if mutable.state.stage.is_terminal() {
            return;
        }
        mutable.state.set_stage(stage);
        mutable.state.account_id = account_id;
        mutable.state.error_code = error_code.map(str::to_owned);
        mutable.terminal_at = Some(Instant::now());
        mutable.scan_tx.take();
        mutable.check_code_tx.take();
        mutable.permit.take();
    }

    fn cancel(&self) -> bool {
        let mut mutable = self
            .mutable
            .lock()
            .expect("Matrix OAuth acquire flow poisoned");
        if mutable.finalizing || mutable.state.stage.is_terminal() {
            return false;
        }
        mutable.state.set_stage(MatrixOAuthAcquireStage::Cancelled);
        mutable.terminal_at = Some(Instant::now());
        mutable.scan_tx.take();
        mutable.check_code_tx.take();
        mutable.permit.take();
        drop(mutable);
        self.cancel.cancel();
        true
    }
}

struct MatrixOAuthAcquireInner {
    store: Store,
    config: SyncConfig,
    lifecycle: AccountLifecycle,
    registrations: MatrixOAuthRegistrationManager,
    flows: Mutex<HashMap<Uuid, Arc<Flow>>>,
    capacity: Arc<Semaphore>,
    tracker: TaskTracker,
    engine_cancel: CancellationToken,
}

/// Cloneable runtime owner for pre-account QR login flows.
#[derive(Clone)]
pub struct MatrixOAuthAcquireEngine {
    inner: Arc<MatrixOAuthAcquireInner>,
}

impl MatrixOAuthAcquireEngine {
    pub(crate) fn new(
        store: Store,
        config: SyncConfig,
        lifecycle: AccountLifecycle,
        tracker: TaskTracker,
        engine_cancel: CancellationToken,
    ) -> Self {
        let registrations =
            MatrixOAuthRegistrationManager::new(store.clone(), config.matrix_oauth.clone());
        Self {
            inner: Arc::new(MatrixOAuthAcquireInner {
                store,
                config,
                lifecycle,
                registrations,
                flows: Mutex::new(HashMap::new()),
                capacity: Arc::new(Semaphore::new(MAX_CONCURRENT_FLOWS)),
                tracker,
                engine_cancel,
            }),
        }
    }

    pub async fn create(
        &self,
        expected_user_id: &str,
        presentation: MatrixOAuthAcquirePresentation,
    ) -> Result<MatrixOAuthAcquireState, MatrixOAuthAcquireError> {
        self.reap_expired();
        if expected_user_id.len() > MAX_USER_ID_BYTES
            || OwnedUserId::try_from(expected_user_id).is_err()
        {
            return Err(MatrixOAuthAcquireError::InvalidUserId);
        }
        let permit = self
            .inner
            .capacity
            .clone()
            .try_acquire_owned()
            .map_err(|_| MatrixOAuthAcquireError::Capacity)?;
        if self
            .inner
            .flows
            .lock()
            .expect("Matrix OAuth acquire registry poisoned")
            .len()
            >= MAX_RETAINED_FLOWS
        {
            return Err(MatrixOAuthAcquireError::Capacity);
        }
        let flow_id = Uuid::new_v4();
        let staging_dir_name = flow_id.to_string();
        self.inner
            .lifecycle
            .reserve_matrix_oauth_acquire(
                flow_id,
                expected_user_id,
                presentation.as_str(),
                &staging_dir_name,
            )
            .await
            .map_err(create_lifecycle_error)?;

        let (scan_tx, scan_rx) = oneshot::channel();
        let (check_code_tx, check_code_rx) = oneshot::channel();
        let cancel = self.inner.engine_cancel.child_token();
        let flow = Arc::new(Flow {
            mutable: Mutex::new(FlowMutable {
                state: MatrixOAuthAcquireState::new(
                    flow_id,
                    expected_user_id.to_owned(),
                    presentation,
                ),
                terminal_at: None,
                scan_tx: Some(scan_tx),
                check_code_tx: Some(check_code_tx),
                finalizing: false,
                permit: Some(permit),
            }),
            cancel,
            staging_dir_name,
        });
        let inserted = {
            let mut flows = self
                .inner
                .flows
                .lock()
                .expect("Matrix OAuth acquire registry poisoned");
            if flows.len() >= MAX_RETAINED_FLOWS {
                false
            } else {
                flows.insert(flow_id, flow.clone());
                true
            }
        };
        if !inserted {
            let abandoned = self
                .inner
                .store
                .abandon_matrix_oauth_acquire(flow_id)
                .await
                .map_err(|err| {
                    tracing::error!(
                        %flow_id,
                        error_class = %store_error_class(&err),
                        "releasing a capacity-refused Matrix OAuth breadcrumb failed"
                    );
                    MatrixOAuthAcquireError::Internal
                })?;
            if !abandoned {
                tracing::error!(
                    %flow_id,
                    "capacity-refused Matrix OAuth breadcrumb disappeared before cleanup"
                );
                return Err(MatrixOAuthAcquireError::Internal);
            }
            return Err(MatrixOAuthAcquireError::Capacity);
        }

        let driver = self.clone();
        let task_flow = flow.clone();
        let driver_span = tracing::info_span!(
            "matrix_oauth_qr_login",
            %flow_id,
            role = "acquire",
            presentation = presentation.as_str()
        );
        self.inner.tracker.spawn(
            async move {
                driver.drive(task_flow, scan_rx, check_code_rx).await;
            }
            .instrument(driver_span),
        );
        tracing::info!(
            %flow_id,
            role = "acquire",
            presentation = presentation.as_str(),
            "Matrix OAuth QR login flow created"
        );
        Ok(flow.snapshot())
    }

    pub fn get(&self, flow_id: Uuid) -> Result<MatrixOAuthAcquireState, MatrixOAuthAcquireError> {
        self.reap_expired();
        self.inner
            .flows
            .lock()
            .expect("Matrix OAuth acquire registry poisoned")
            .get(&flow_id)
            .map(|flow| flow.snapshot())
            .ok_or(MatrixOAuthAcquireError::NotFound(flow_id))
    }

    pub fn submit_scan(
        &self,
        flow_id: Uuid,
        qr_code_data: &str,
    ) -> Result<MatrixOAuthAcquireState, MatrixOAuthAcquireError> {
        let parsed = parse_qr_payload(qr_code_data)?;
        let flow = self.flow(flow_id)?;
        let mut mutable = flow
            .mutable
            .lock()
            .expect("Matrix OAuth acquire flow poisoned");
        if mutable.state.presentation != MatrixOAuthAcquirePresentation::Scan
            || mutable.state.stage != MatrixOAuthAcquireStage::Starting
            || mutable.finalizing
        {
            return Err(MatrixOAuthAcquireError::WrongStage);
        }
        let tx = mutable
            .scan_tx
            .take()
            .ok_or(MatrixOAuthAcquireError::WrongStage)?;
        tx.send(parsed)
            .map_err(|_| MatrixOAuthAcquireError::WrongStage)?;
        Ok(mutable.state.clone())
    }

    pub fn submit_check_code(
        &self,
        flow_id: Uuid,
        check_code: &str,
    ) -> Result<MatrixOAuthAcquireState, MatrixOAuthAcquireError> {
        let value = parse_check_code(check_code)?;
        let flow = self.flow(flow_id)?;
        let mut mutable = flow
            .mutable
            .lock()
            .expect("Matrix OAuth acquire flow poisoned");
        if mutable.state.presentation != MatrixOAuthAcquirePresentation::Display
            || mutable.state.stage != MatrixOAuthAcquireStage::CheckCodeRequired
            || mutable.finalizing
        {
            return Err(MatrixOAuthAcquireError::WrongStage);
        }
        let tx = mutable
            .check_code_tx
            .take()
            .ok_or(MatrixOAuthAcquireError::WrongStage)?;
        tx.send(value)
            .map_err(|_| MatrixOAuthAcquireError::WrongStage)?;
        Ok(mutable.state.clone())
    }

    /// Idempotent cancellation. Unknown/expired identifiers are deliberately a
    /// no-op so repeated DELETE requests have the same result.
    pub fn cancel(&self, flow_id: Uuid) {
        let flow = self
            .inner
            .flows
            .lock()
            .expect("Matrix OAuth acquire registry poisoned")
            .get(&flow_id)
            .cloned();
        let Some(flow) = flow else { return };
        if flow.cancel() {
            let presentation = flow.snapshot().presentation.as_str();
            tracing::info!(%flow_id, role = "acquire", presentation, "Matrix OAuth QR login flow cancelled");
        }
    }

    pub(crate) async fn reap_loop(self, cancel: CancellationToken) {
        loop {
            tokio::select! {
                _ = cancel.cancelled() => break,
                _ = tokio::time::sleep(REAPER_INTERVAL) => self.reap_expired(),
            }
        }
    }

    fn flow(&self, flow_id: Uuid) -> Result<Arc<Flow>, MatrixOAuthAcquireError> {
        self.inner
            .flows
            .lock()
            .expect("Matrix OAuth acquire registry poisoned")
            .get(&flow_id)
            .cloned()
            .ok_or(MatrixOAuthAcquireError::NotFound(flow_id))
    }

    fn reap_expired(&self) {
        let now = Instant::now();
        self.inner
            .flows
            .lock()
            .expect("Matrix OAuth acquire registry poisoned")
            .retain(|_, flow| {
                flow.mutable
                    .lock()
                    .expect("Matrix OAuth acquire flow poisoned")
                    .terminal_at
                    .is_none_or(|terminal_at| now.duration_since(terminal_at) < TERMINAL_RETENTION)
            });
    }

    async fn drive(
        &self,
        flow: Arc<Flow>,
        scan_rx: oneshot::Receiver<QrCodeData>,
        check_code_rx: oneshot::Receiver<u8>,
    ) {
        let snapshot = flow.snapshot();
        let flow_id = snapshot.flow_id;
        let presentation = snapshot.presentation.as_str();
        let deadline = tokio::time::Instant::now() + FLOW_TTL;
        // The protocol driver owns the client all the way through timeout and
        // cancellation handling. Dropping that future from an outer timeout
        // would lose the only opportunity to revoke a session minted just
        // before the deadline.
        let result = self
            .drive_protocol(flow.clone(), scan_rx, check_code_rx, deadline)
            .await;

        match result {
            Ok((client, session)) => {
                if flow.cancel.is_cancelled() || !flow.claim_finalization() {
                    self.cleanup_precommit(&flow, Some(&client)).await;
                    return;
                }
                match self
                    .inner
                    .lifecycle
                    .finalize_matrix_oauth_acquire(
                        flow_id,
                        &flow.staging_dir_name,
                        &flow.snapshot().expected_user_id,
                        client,
                        session,
                    )
                    .await
                {
                    Ok(account_id) => {
                        flow.terminal(MatrixOAuthAcquireStage::Done, Some(account_id), None);
                        tracing::info!(
                            %flow_id,
                            %account_id,
                            role = "acquire",
                            presentation,
                            stage = "done",
                            "Matrix OAuth QR login flow completed"
                        );
                    }
                    Err(failure) => {
                        let code = lifecycle_failure_code(&failure.error);
                        // Cleanup inspects the durable commit point before it
                        // revokes anything. Once the encrypted session has
                        // committed, boot reconciliation must retain and adopt
                        // that still-valid session instead.
                        self.cleanup_precommit(&flow, failure.acquisition_client.as_ref())
                            .await;
                        flow.terminal(MatrixOAuthAcquireStage::Failed, None, Some(code));
                        tracing::warn!(
                            %flow_id,
                            role = "acquire",
                            presentation,
                            stage = "failed",
                            error_code = code,
                            "Matrix OAuth QR login finalization failed"
                        );
                    }
                }
            }
            Err(DriverFailure::Cancelled) => {
                self.cleanup_precommit(&flow, None).await;
                flow.terminal(MatrixOAuthAcquireStage::Cancelled, None, None);
            }
            Err(failure) => {
                let code = failure.code();
                self.cleanup_precommit(&flow, None).await;
                flow.terminal(MatrixOAuthAcquireStage::Failed, None, Some(code));
                tracing::warn!(
                    %flow_id,
                    role = "acquire",
                    presentation,
                    stage = "failed",
                    error_code = code,
                    "Matrix OAuth QR login flow failed"
                );
            }
        }
    }

    async fn drive_protocol(
        &self,
        flow: Arc<Flow>,
        scan_rx: oneshot::Receiver<QrCodeData>,
        check_code_rx: oneshot::Receiver<u8>,
        deadline: tokio::time::Instant,
    ) -> Result<(Client, matrix_sdk::authentication::oauth::OAuthSession), DriverFailure> {
        let snapshot = flow.snapshot();
        let client = match snapshot.presentation {
            MatrixOAuthAcquirePresentation::Display => {
                let user_id = OwnedUserId::try_from(snapshot.expected_user_id.as_str())
                    .map_err(|_| DriverFailure::InvalidQr)?;
                build_matrix_oauth_acquire_client(
                    &self.inner.config,
                    &flow.staging_dir_name,
                    user_id.server_name().as_str(),
                )
                .await
                .map_err(classify_client_build_error)?
            }
            MatrixOAuthAcquirePresentation::Scan => {
                let qr = tokio::select! {
                    _ = flow.cancel.cancelled() => return Err(DriverFailure::Cancelled),
                    _ = tokio::time::sleep_until(deadline) => return Err(DriverFailure::Timeout),
                    qr = scan_rx => qr.map_err(|_| DriverFailure::Cancelled)?,
                };
                let server = qr_server(&qr)?;
                let client = build_matrix_oauth_acquire_client(
                    &self.inner.config,
                    &flow.staging_dir_name,
                    &server,
                )
                .await
                .map_err(classify_client_build_error)?;
                self.inner
                    .registrations
                    .prepare(&client)
                    .await
                    .map_err(classify_registration_error)?;
                if let Err(failure) = self.run_scan_login(&flow, &client, &qr, deadline).await {
                    if client.oauth().full_session().is_some() {
                        best_effort_revoke(&client).await;
                    }
                    return Err(failure);
                }
                return self.validate_completed_client(&flow, client).await;
            }
        };

        self.inner
            .registrations
            .prepare(&client)
            .await
            .map_err(classify_registration_error)?;
        if let Err(failure) = self
            .run_display_login(&flow, &client, check_code_rx, deadline)
            .await
        {
            if client.oauth().full_session().is_some() {
                best_effort_revoke(&client).await;
            }
            return Err(failure);
        }
        self.validate_completed_client(&flow, client).await
    }

    async fn run_scan_login(
        &self,
        flow: &Arc<Flow>,
        client: &Client,
        qr: &QrCodeData,
        deadline: tokio::time::Instant,
    ) -> Result<(), DriverFailure> {
        let oauth = client.oauth();
        let login = oauth.login_with_qr_code(None).scan(qr);
        let mut progress = ProgressUntilClosed::new(Box::pin(login.subscribe_to_progress()));
        let mut login = login.into_future();
        loop {
            tokio::select! {
                _ = flow.cancel.cancelled() => return Err(DriverFailure::Cancelled),
                _ = tokio::time::sleep_until(deadline) => return Err(DriverFailure::Timeout),
                result = &mut login => return result.map_err(classify_qr_error),
                next = progress.next() => match next {
                    Some(LoginProgress::Starting) => {}
                    Some(LoginProgress::EstablishingSecureChannel(QrProgress { check_code })) => {
                        flow.update(|state| {
                            state.set_stage(MatrixOAuthAcquireStage::CheckCodeToDisplay);
                            state.check_code = Some(format!("{:02}", check_code.to_digit()));
                        });
                    }
                    Some(LoginProgress::WaitingForToken { user_code }) => {
                        flow.update(|state| {
                            state.set_stage(MatrixOAuthAcquireStage::WaitingForAuthorization);
                            state.authorization_user_code = Some(user_code);
                        });
                    }
                    Some(LoginProgress::SyncingSecrets) => {
                        flow.update(|state| state.set_stage(MatrixOAuthAcquireStage::SyncingSecrets));
                    }
                    Some(LoginProgress::Done) | None => {}
                }
            }
        }
    }

    async fn run_display_login(
        &self,
        flow: &Arc<Flow>,
        client: &Client,
        mut check_code_rx: oneshot::Receiver<u8>,
        deadline: tokio::time::Instant,
    ) -> Result<(), DriverFailure> {
        let oauth = client.oauth();
        let login = oauth.login_with_qr_code(None).generate();
        let mut progress = ProgressUntilClosed::new(Box::pin(login.subscribe_to_progress()));
        let mut login = login.into_future();
        let mut check_sender: Option<CheckCodeSender> = None;
        loop {
            tokio::select! {
                _ = flow.cancel.cancelled() => return Err(DriverFailure::Cancelled),
                _ = tokio::time::sleep_until(deadline) => return Err(DriverFailure::Timeout),
                result = &mut login => return result.map_err(classify_qr_error),
                code = &mut check_code_rx, if check_sender.is_some() => {
                    let code = code.map_err(|_| DriverFailure::Cancelled)?;
                    check_sender.take().expect("guarded sender")
                        .send(code).await.map_err(|_| DriverFailure::InvalidCheckCode)?;
                }
                next = progress.next() => match next {
                    Some(LoginProgress::Starting) => {}
                    Some(LoginProgress::EstablishingSecureChannel(GeneratedQrProgress::QrReady(qr))) => {
                        flow.update(|state| {
                            state.set_stage(MatrixOAuthAcquireStage::QrReady);
                            state.qr_code_data = Some(qr.to_base64());
                        });
                    }
                    Some(LoginProgress::EstablishingSecureChannel(GeneratedQrProgress::QrScanned(sender))) => {
                        check_sender = Some(sender);
                        flow.update(|state| state.set_stage(MatrixOAuthAcquireStage::CheckCodeRequired));
                    }
                    Some(LoginProgress::WaitingForToken { user_code }) => {
                        flow.update(|state| {
                            state.set_stage(MatrixOAuthAcquireStage::WaitingForAuthorization);
                            state.authorization_user_code = Some(user_code);
                        });
                    }
                    Some(LoginProgress::SyncingSecrets) => {
                        flow.update(|state| state.set_stage(MatrixOAuthAcquireStage::SyncingSecrets));
                    }
                    Some(LoginProgress::Done) | None => {}
                }
            }
        }
    }

    async fn validate_completed_client(
        &self,
        flow: &Arc<Flow>,
        client: Client,
    ) -> Result<(Client, matrix_sdk::authentication::oauth::OAuthSession), DriverFailure> {
        let validation = async {
            let who = tokio::time::timeout(WHOAMI_TIMEOUT, client.whoami())
                .await
                .map_err(|_| {
                    let failure = DriverFailure::Timeout;
                    log_driver_failure("identity_validation", &failure, None);
                    failure
                })?
                .map_err(|error| {
                    let failure = DriverFailure::Upstream;
                    let http_status = error
                        .as_client_api_error()
                        .map(|response| response.status_code.as_u16());
                    log_driver_failure("identity_validation", &failure, http_status);
                    failure
                })?;
            if who.user_id.as_str() != flow.snapshot().expected_user_id {
                let failure = DriverFailure::UserMismatch;
                log_driver_failure("identity_validation", &failure, None);
                return Err(failure);
            }
            let session = client.oauth().full_session().ok_or_else(|| {
                let failure = DriverFailure::Internal;
                log_driver_failure("session_validation", &failure, None);
                failure
            })?;
            if session.user.tokens.refresh_token.is_none() {
                let failure = DriverFailure::Upstream;
                log_driver_failure("session_validation", &failure, None);
                return Err(failure);
            }
            Ok(session)
        }
        .await;
        match validation {
            Ok(session) => Ok((client, session)),
            Err(failure) => {
                if client.oauth().full_session().is_some() {
                    best_effort_revoke(&client).await;
                }
                Err(failure)
            }
        }
    }

    async fn cleanup_precommit(&self, flow: &Flow, client: Option<&Client>) {
        let flow_id = flow.snapshot().flow_id;
        let is_staging = match self
            .inner
            .store
            .matrix_oauth_acquire_is_staging(flow_id)
            .await
        {
            Ok(is_staging) => is_staging,
            Err(err) => {
                tracing::error!(
                %flow_id,
                error_class = %store_error_class(&err),
                "failed to inspect Matrix OAuth acquire breadcrumb during cleanup"
                );
                return;
            }
        };
        // A false result means finalization crossed the durable commit point (or
        // already finished); boot reconciliation owns any remaining resources.
        if !is_staging {
            return;
        }
        if let Some(client) = client {
            best_effort_revoke(client).await;
        }
        if remove_matrix_oauth_acquire_staging(&self.inner.config, &flow.staging_dir_name)
            .await
            .is_err()
        {
            tracing::warn!(%flow_id, error_class = "filesystem", "failed to remove Matrix OAuth staging store");
            return;
        }
        if let Err(err) = self.inner.store.abandon_matrix_oauth_acquire(flow_id).await {
            tracing::error!(
                %flow_id,
                error_class = %store_error_class(&err),
                "failed to abandon Matrix OAuth acquire breadcrumb"
            );
        }
    }
}

#[derive(Debug)]
enum DriverFailure {
    Cancelled,
    Timeout,
    Unsupported,
    InvalidQr,
    InvalidCheckCode,
    RendezvousExpired,
    UserMismatch,
    Upstream,
    Internal,
}

impl DriverFailure {
    fn code(&self) -> &'static str {
        match self {
            Self::Cancelled => "cancelled",
            Self::Timeout => "timeout",
            Self::Unsupported => "unsupported",
            Self::InvalidQr => "invalid_qr",
            Self::InvalidCheckCode => "invalid_check_code",
            Self::RendezvousExpired => "rendezvous_expired",
            Self::UserMismatch => "user_mismatch",
            Self::Upstream => "upstream",
            Self::Internal => "internal",
        }
    }
}

fn qr_server(qr: &QrCodeData) -> Result<String, DriverFailure> {
    match qr.intent_data() {
        QrCodeIntentData::Msc4108 {
            data: Msc4108IntentData::Reciprocate { server_name },
            ..
        } => validate_qr_server_name_or_url(server_name)
            .map(|()| server_name.clone())
            .map_err(|_| DriverFailure::InvalidQr),
        QrCodeIntentData::Msc4388 { base_url, .. } if qr.intent() == QrCodeIntent::Reciprocate => {
            validate_qr_url(base_url)
                .map(|()| base_url.to_string())
                .map_err(|_| DriverFailure::InvalidQr)
        }
        _ => Err(DriverFailure::InvalidQr),
    }
}

fn parse_qr_payload(value: &str) -> Result<QrCodeData, MatrixOAuthAcquireError> {
    if value.is_empty() || value.len() > MAX_QR_BASE64_BYTES {
        return Err(MatrixOAuthAcquireError::InvalidInput(
            "QR payload has an invalid size",
        ));
    }
    let parsed = QrCodeData::from_base64(value)
        .map_err(|_| MatrixOAuthAcquireError::InvalidInput("QR payload is malformed"))?;
    if parsed.intent() != QrCodeIntent::Reciprocate {
        return Err(MatrixOAuthAcquireError::InvalidInput(
            "QR payload has the wrong intent",
        ));
    }
    match parsed.intent_data() {
        QrCodeIntentData::Msc4108 {
            data: Msc4108IntentData::Reciprocate { server_name },
            rendezvous_url,
        } => {
            validate_qr_server_name_or_url(server_name)?;
            validate_qr_url(rendezvous_url)?;
        }
        QrCodeIntentData::Msc4388 { base_url, .. } => validate_qr_url(base_url)?,
        _ => {
            return Err(MatrixOAuthAcquireError::InvalidInput(
                "QR payload has the wrong intent",
            ))
        }
    }
    Ok(parsed)
}

fn validate_qr_server_name_or_url(value: &str) -> Result<(), MatrixOAuthAcquireError> {
    if OwnedServerName::try_from(value).is_ok() {
        return Ok(());
    }
    let url = url::Url::parse(value).map_err(|_| {
        MatrixOAuthAcquireError::InvalidInput(
            "QR payload contains an invalid Matrix server name or homeserver URL",
        )
    })?;
    validate_qr_url(&url)
}

fn validate_qr_url(url: &url::Url) -> Result<(), MatrixOAuthAcquireError> {
    let host = url.host_str().ok_or(MatrixOAuthAcquireError::InvalidInput(
        "QR payload contains a URL without a host",
    ))?;
    let host = host.trim_start_matches('[').trim_end_matches(']');
    let loopback = host == "localhost"
        || host
            .parse::<std::net::IpAddr>()
            .is_ok_and(|ip| ip.is_loopback());
    let safe_scheme = url.scheme() == "https" || (url.scheme() == "http" && loopback);
    if !safe_scheme || !url.username().is_empty() || url.password().is_some() {
        return Err(MatrixOAuthAcquireError::InvalidInput(
            "QR payload contains an unsafe URL",
        ));
    }
    Ok(())
}

fn parse_check_code(value: &str) -> Result<u8, MatrixOAuthAcquireError> {
    if value.len() != 2 || !value.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err(MatrixOAuthAcquireError::InvalidInput(
            "check code must contain exactly two digits",
        ));
    }
    value
        .parse::<u8>()
        .map_err(|_| MatrixOAuthAcquireError::InvalidInput("check code is invalid"))
}

fn classify_qr_error(error: QRCodeLoginError) -> DriverFailure {
    let (phase, failure, http_status) = match &error {
        QRCodeLoginError::OAuth(DeviceAuthorizationOAuthError::NoDeviceAuthorizationEndpoint) => {
            ("device_authorization", DriverFailure::Unsupported, None)
        }
        QRCodeLoginError::OAuth(_) => ("device_authorization", DriverFailure::Upstream, None),
        QRCodeLoginError::SecureChannel(SecureChannelError::RendezvousChannel(http_error)) => {
            let response = http_error.as_client_api_error();
            let failure = if response.is_some_and(|error| error.is_endpoint_not_implemented()) {
                DriverFailure::Unsupported
            } else {
                DriverFailure::Upstream
            };
            (
                "rendezvous",
                failure,
                response.map(|error| error.status_code.as_u16()),
            )
        }
        QRCodeLoginError::SecureChannel(SecureChannelError::InvalidCheckCode) => {
            ("secure_channel", DriverFailure::InvalidCheckCode, None)
        }
        QRCodeLoginError::SecureChannel(_) => ("secure_channel", DriverFailure::Upstream, None),
        QRCodeLoginError::NotFound => ("rendezvous", DriverFailure::RendezvousExpired, None),
        QRCodeLoginError::CrossProcessRefreshLock(_) => {
            ("session_activation", DriverFailure::Upstream, None)
        }
        QRCodeLoginError::UserIdDiscovery(_) => {
            ("identity_discovery", DriverFailure::Upstream, None)
        }
        QRCodeLoginError::SessionTokens(_) => ("session_activation", DriverFailure::Upstream, None),
        QRCodeLoginError::DeviceKeyUpload(_) => {
            ("device_key_upload", DriverFailure::Upstream, None)
        }
        QRCodeLoginError::SecretImport(_) => ("secret_import", DriverFailure::Upstream, None),
        QRCodeLoginError::ServerReset(_) => ("homeserver_reset", DriverFailure::Upstream, None),
        QRCodeLoginError::LoginFailure { .. } | QRCodeLoginError::UnexpectedMessage { .. } => {
            ("peer_authorization", DriverFailure::Upstream, None)
        }
    };
    log_driver_failure(phase, &failure, http_status);
    failure
}

fn log_driver_failure(phase: &'static str, failure: &DriverFailure, http_status: Option<u16>) {
    if let Some(http_status) = http_status {
        tracing::warn!(
            phase,
            error_class = failure.code(),
            http_status,
            "Matrix OAuth QR protocol step failed"
        );
    } else {
        tracing::warn!(
            phase,
            error_class = failure.code(),
            "Matrix OAuth QR protocol step failed"
        );
    }
}

fn classify_registration_error(error: SyncError) -> DriverFailure {
    let failure = match &error {
        SyncError::MatrixOAuthUnavailable => DriverFailure::Unsupported,
        SyncError::MatrixOAuthConfiguration => DriverFailure::Internal,
        SyncError::MatrixOAuthLocalState
        | SyncError::Store(_)
        | SyncError::MissingStoreKey
        | SyncError::MissingDeviceId(_)
        | SyncError::NoCredential(_) => DriverFailure::Internal,
        SyncError::Sdk(_) | SyncError::AuthFailed(_) => DriverFailure::Upstream,
    };
    let phase = match &error {
        SyncError::MatrixOAuthConfiguration => "oauth_registration_config",
        SyncError::MatrixOAuthLocalState
        | SyncError::Store(_)
        | SyncError::MissingStoreKey
        | SyncError::MissingDeviceId(_)
        | SyncError::NoCredential(_) => "oauth_registration_state",
        _ => "oauth_registration",
    };
    log_driver_failure(phase, &failure, None);
    failure
}

fn classify_client_build_error(error: MatrixOAuthAcquireClientError) -> DriverFailure {
    let (phase, failure) = match error {
        MatrixOAuthAcquireClientError::Configuration => {
            ("client_build_config", DriverFailure::Internal)
        }
        MatrixOAuthAcquireClientError::LocalStorage => {
            ("client_build_storage", DriverFailure::Internal)
        }
        MatrixOAuthAcquireClientError::Upstream => ("client_build", DriverFailure::Upstream),
    };
    log_driver_failure(phase, &failure, None);
    failure
}

fn lifecycle_failure_code(error: &LifecycleError) -> &'static str {
    match error {
        LifecycleError::AlreadyActive(_)
        | LifecycleError::BeingDeleted(_)
        | LifecycleError::Draining(_)
        | LifecycleError::LoginFinalizing(_) => "conflict",
        LifecycleError::DeviceNotVerified => "device_not_verified",
        LifecycleError::AuthFailed(_) => "user_mismatch",
        LifecycleError::Upstream(_) => "upstream",
        LifecycleError::Store(_) => "internal",
        _ => "internal",
    }
}

async fn best_effort_revoke(client: &Client) {
    match tokio::time::timeout(REVOCATION_TIMEOUT, client.oauth().logout()).await {
        Ok(Ok(())) => {}
        Ok(Err(_)) => tracing::warn!(
            role = "acquire",
            error_class = "upstream",
            "Matrix OAuth QR login session revocation failed"
        ),
        Err(_) => tracing::warn!(
            role = "acquire",
            error_class = "timeout",
            "Matrix OAuth QR login session revocation timed out"
        ),
    }
}

fn store_error_class(error: &axon_store::StoreError) -> &'static str {
    match error {
        axon_store::StoreError::Sqlx(_) => "database",
        axon_store::StoreError::Migrate(_) | axon_store::StoreError::EmbeddedMigration(_) => {
            "migration"
        }
        _ => "store",
    }
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::{AtomicUsize, Ordering};

    use super::*;
    use matrix_sdk::ruma::api::error::{
        Error as MatrixApiError, ErrorBody, ErrorKind, FromHttpResponseError, StandardErrorBody,
    };
    use matrix_sdk::ruma::exports::http::StatusCode as HttpStatus;
    use matrix_sdk::{HttpError, RumaApiError};

    #[tokio::test]
    async fn closed_progress_stream_is_not_polled_again() {
        let polls = Arc::new(AtomicUsize::new(0));
        let counted = Arc::clone(&polls);
        let stream = futures_util::stream::poll_fn(move |_| {
            counted.fetch_add(1, Ordering::SeqCst);
            std::task::Poll::Ready(None::<()>)
        });
        let mut progress = ProgressUntilClosed::new(Box::pin(stream));

        assert!(progress.next().await.is_none());
        assert_eq!(polls.load(Ordering::SeqCst), 1);
        assert!(
            tokio::time::timeout(Duration::from_millis(10), progress.next())
                .await
                .is_err(),
            "a closed progress stream must stay disabled"
        );
        assert_eq!(
            polls.load(Ordering::SeqCst),
            1,
            "the underlying closed stream must not be polled repeatedly"
        );
    }

    #[test]
    fn lifecycle_reservation_distinguishes_login_conflicts() {
        let account_id = Uuid::new_v4();
        assert!(matches!(
            create_lifecycle_error(LifecycleError::AlreadyActive(account_id)),
            MatrixOAuthAcquireError::AccountAlreadyActive
        ));
        assert!(matches!(
            create_lifecycle_error(LifecycleError::BeingDeleted(account_id)),
            MatrixOAuthAcquireError::AccountBeingDeleted
        ));
        assert!(matches!(
            create_lifecycle_error(LifecycleError::Draining(account_id)),
            MatrixOAuthAcquireError::AccountDraining
        ));
        assert!(matches!(
            create_lifecycle_error(LifecycleError::LoginFinalizing(
                "@alice:example.org".to_owned()
            )),
            MatrixOAuthAcquireError::FlowAlreadyExists
        ));
    }

    #[test]
    fn stage_transition_exposes_only_stage_appropriate_data() {
        let mut state = MatrixOAuthAcquireState::new(
            Uuid::new_v4(),
            "@alice:example.org".to_owned(),
            MatrixOAuthAcquirePresentation::Display,
        );
        state.set_stage(MatrixOAuthAcquireStage::QrReady);
        state.qr_code_data = Some("opaque".to_owned());
        state.set_stage(MatrixOAuthAcquireStage::CheckCodeRequired);
        assert!(state.qr_code_data.is_none());
        assert!(state.check_code.is_none());
        assert!(state.authorization_user_code.is_none());
        assert!(state.account_id.is_none());
        assert!(state.error_code.is_none());
    }

    #[test]
    fn stable_failure_codes_cover_every_driver_failure() {
        let cases = [
            (DriverFailure::Cancelled, "cancelled"),
            (DriverFailure::Timeout, "timeout"),
            (DriverFailure::Unsupported, "unsupported"),
            (DriverFailure::InvalidQr, "invalid_qr"),
            (DriverFailure::InvalidCheckCode, "invalid_check_code"),
            (DriverFailure::RendezvousExpired, "rendezvous_expired"),
            (DriverFailure::UserMismatch, "user_mismatch"),
            (DriverFailure::Upstream, "upstream"),
            (DriverFailure::Internal, "internal"),
        ];
        for (failure, expected) in cases {
            assert_eq!(failure.code(), expected);
        }
    }

    #[test]
    fn unavailable_oauth_discovery_is_not_a_transient_upstream_failure() {
        assert!(matches!(
            classify_registration_error(SyncError::MatrixOAuthUnavailable),
            DriverFailure::Unsupported
        ));
        assert!(matches!(
            classify_registration_error(SyncError::Sdk("network failure".to_owned())),
            DriverFailure::Upstream
        ));
        assert!(matches!(
            classify_registration_error(SyncError::MatrixOAuthConfiguration),
            DriverFailure::Internal
        ));
        assert!(matches!(
            classify_registration_error(SyncError::MatrixOAuthLocalState),
            DriverFailure::Internal
        ));
    }

    #[test]
    fn client_build_failures_distinguish_local_and_upstream_causes() {
        assert!(matches!(
            classify_client_build_error(MatrixOAuthAcquireClientError::Configuration),
            DriverFailure::Internal
        ));
        assert!(matches!(
            classify_client_build_error(MatrixOAuthAcquireClientError::LocalStorage),
            DriverFailure::Internal
        ));
        assert!(matches!(
            classify_client_build_error(MatrixOAuthAcquireClientError::Upstream),
            DriverFailure::Upstream
        ));
    }

    #[test]
    fn missing_rendezvous_endpoint_is_unsupported() {
        let body = ErrorBody::Standard(StandardErrorBody::new(
            ErrorKind::Unrecognized,
            "Unrecognized request".to_owned(),
        ));
        let error = HttpError::Api(Box::new(FromHttpResponseError::Server(
            RumaApiError::MatrixError(MatrixApiError::new(HttpStatus::NOT_FOUND, body)),
        )));
        let error = QRCodeLoginError::SecureChannel(SecureChannelError::RendezvousChannel(error));

        assert!(matches!(
            classify_qr_error(error),
            DriverFailure::Unsupported
        ));
    }

    #[test]
    fn qr_and_check_code_inputs_are_bounded_before_use() {
        assert!(matches!(
            parse_qr_payload(&"A".repeat(MAX_QR_BASE64_BYTES + 1)),
            Err(MatrixOAuthAcquireError::InvalidInput(_))
        ));
        assert!(matches!(
            parse_qr_payload("not base64 or QR data"),
            Err(MatrixOAuthAcquireError::InvalidInput(_))
        ));
        assert_eq!(parse_check_code("00").unwrap(), 0);
        assert_eq!(parse_check_code("09").unwrap(), 9);
        assert_eq!(parse_check_code("99").unwrap(), 99);
        for invalid in ["", "1", "100", "a1", "１２"] {
            assert!(matches!(
                parse_check_code(invalid),
                Err(MatrixOAuthAcquireError::InvalidInput(_))
            ));
        }
        for unsafe_url in [
            "file:///etc/passwd",
            "http://example.org/rendezvous",
            "https://user:password@example.org/rendezvous",
        ] {
            assert!(matches!(
                validate_qr_url(&url::Url::parse(unsafe_url).unwrap()),
                Err(MatrixOAuthAcquireError::InvalidInput(_))
            ));
        }
        for safe_url in [
            "https://example.org/rendezvous",
            "http://localhost:8008/rendezvous",
            "http://127.0.0.1:8008/rendezvous",
            "http://[::1]:8008/rendezvous",
        ] {
            validate_qr_url(&url::Url::parse(safe_url).unwrap()).unwrap();
        }
    }

    #[test]
    fn msc4108_reciprocate_accepts_element_homeserver_url() {
        // matrix-rust-sdk's MSC4108 interop vector uses a homeserver URL in
        // the legacy `server_name` field, as Element X does in production.
        let payload = concat!(
            "TUFUUklYAgS0yzZ1QVpQ1jlnoxWX3d5jrWRFfELxjS2gN7pz9y+3PABaaHR0",
            "cHM6Ly9zeW5hcHNlLW9pZGMubGFiLmVsZW1lbnQuZGV2L19zeW5hcHNlL2Ns",
            "aWVudC9yZW5kZXp2b3VzLzAxSFg5SzAwUTFINktQRDQ3RUc0RzFUM1hHACVo",
            "dHRwczovL3N5bmFwc2Utb2lkYy5sYWIuZWxlbWVudC5kZXYv",
        );

        let qr = parse_qr_payload(payload).expect("Element-style QR payload should be valid");
        assert_eq!(
            qr_server(&qr).unwrap(),
            "https://synapse-oidc.lab.element.dev/"
        );
    }

    #[test]
    fn cancellation_and_finalization_have_one_atomic_owner() {
        let semaphore = Arc::new(Semaphore::new(1));
        let permit = semaphore.try_acquire_owned().unwrap();
        let (scan_tx, _scan_rx) = oneshot::channel();
        let (check_code_tx, _check_code_rx) = oneshot::channel();
        let flow = Flow {
            mutable: Mutex::new(FlowMutable {
                state: MatrixOAuthAcquireState::new(
                    Uuid::new_v4(),
                    "@alice:example.org".to_owned(),
                    MatrixOAuthAcquirePresentation::Display,
                ),
                terminal_at: None,
                scan_tx: Some(scan_tx),
                check_code_tx: Some(check_code_tx),
                finalizing: false,
                permit: Some(permit),
            }),
            cancel: CancellationToken::new(),
            staging_dir_name: Uuid::new_v4().to_string(),
        };
        assert!(flow.claim_finalization());
        assert!(!flow.cancel());
        assert_eq!(flow.snapshot().stage, MatrixOAuthAcquireStage::Starting);
    }
}
