//! OAuth refresh tokens: single-use with rotation (M14b, ADR 0054).
//!
//! Separate from [`tokens`](crate::tokens) so the hot-path `TokenVerifier`
//! never needs to know refresh tokens exist — they are only ever touched
//! during a `POST /v1/oauth/token` `grant_type=refresh_token` redemption.
//!
//! Redeeming a refresh token is single-use-with-rotation: the presented token
//! is revoked and a fresh one is minted in its place ([`redeem`](Store::redeem_refresh_token)).
//! Redeeming an *already-revoked* token is reuse — a theft/replay signal — and
//! revokes every other active refresh token for that identity+client in one
//! statement (not a chain-walk): the simplest correct response, and an
//! acceptable "sign this client out everywhere" blast radius for a
//! single-owner server.

use chrono::{DateTime, Duration, Utc};
use sqlx_core::row::Row;
use uuid::Uuid;

use crate::{Store, StoreError};

/// The result of successfully redeeming (and rotating) a refresh token.
#[derive(Debug, Clone)]
pub struct RotatedRefreshToken {
    /// The newly-minted refresh token's row id.
    pub id: Uuid,
    /// The bound identity this refresh token chain belongs to.
    pub oauth_identity_id: Uuid,
    /// The client that redeemed it.
    pub client_id: String,
}

/// Why a refresh-token redemption was rejected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RedeemRefreshTokenError {
    /// No row matches the presented token at all.
    NotFound,
    /// The presented token was valid once but has already been
    /// rotated/revoked — reuse. Every active refresh token for the same
    /// identity+client has been revoked as a side effect of detecting this.
    Reused,
    /// The row matched but has passed its own `expires_at`.
    Expired,
}

/// How long a revoked/expired refresh token row survives before the
/// opportunistic sweep deletes it. Comfortably larger than the reuse-detection
/// horizon (an attacker replaying a rotated token days later still finds the
/// tombstone and trips [`RedeemRefreshTokenError::Reused`]) while still
/// bounding growth to roughly one window's worth of rows.
const SWEEP_WINDOW: Duration = Duration::days(30);

impl Store {
    /// Mint a fresh refresh token row for a newly-bound identity/client pair
    /// (the tail of a Path A/B login, not a rotation). Returns the row id;
    /// the raw secret is generated by the caller (`oauth::tokens`), which also
    /// owns hashing conventions shared with access-token minting.
    ///
    /// Opportunistically sweeps long-dead rows first, same reasoning as
    /// [`create_authorization_request`](crate::Store::create_authorization_request).
    /// [`redeem_refresh_token`](Self::redeem_refresh_token) sweeps too, so
    /// between the two, every *repeatable* write path is covered; the one
    /// exception is `Store::issue_first_oauth_token_pair`'s bootstrap insert,
    /// which bypasses this method entirely but — being a one-time,
    /// bootstrap-gated mint — can only ever add a single row, so it needs no
    /// sweep of its own.
    pub async fn issue_refresh_token(
        &self,
        hash: &str,
        oauth_identity_id: Uuid,
        client_id: &str,
        expires_at: DateTime<Utc>,
    ) -> Result<Uuid, StoreError> {
        self.delete_stale_refresh_tokens().await?;
        let row = sqlx_core::query::query(
            "INSERT INTO oauth_refresh_tokens (hash, oauth_identity_id, client_id, expires_at) \
             VALUES ($1, $2, $3, $4) RETURNING id",
        )
        .bind(hash)
        .bind(oauth_identity_id)
        .bind(client_id)
        .bind(expires_at)
        .fetch_one(&self.pool)
        .await?;
        Ok(row.try_get("id")?)
    }

    /// Redeem a presented refresh token (by its hash): atomically revoke it
    /// and insert its replacement in one statement, returning the new row's
    /// id. If the presented hash doesn't match a currently-active row, falls
    /// back to a plain lookup to distinguish "no such token"
    /// ([`RedeemRefreshTokenError::NotFound`]) from "already
    /// revoked/rotated" ([`RedeemRefreshTokenError::Reused`], which also
    /// revokes the identity+client's other active refresh tokens) or
    /// "expired" ([`RedeemRefreshTokenError::Expired`]).
    ///
    /// Opportunistically sweeps long-dead rows first — see
    /// [`issue_refresh_token`](Self::issue_refresh_token); redemption is the
    /// far higher-volume write path (every refresh, vs. once per new
    /// login/bind), so this is where most of the sweeping actually happens.
    pub async fn redeem_refresh_token(
        &self,
        old_hash: &str,
        new_id: Uuid,
        new_hash: &str,
        new_expires_at: DateTime<Utc>,
    ) -> Result<Result<RotatedRefreshToken, RedeemRefreshTokenError>, StoreError> {
        self.delete_stale_refresh_tokens().await?;
        let rotated = sqlx_core::query::query(
            "WITH revoked AS ( \
                 UPDATE oauth_refresh_tokens \
                    SET revoked_at = now(), replaced_by = $2 \
                  WHERE hash = $1 AND revoked_at IS NULL AND expires_at > now() \
              RETURNING oauth_identity_id, client_id \
             ), inserted AS ( \
                 INSERT INTO oauth_refresh_tokens (id, hash, oauth_identity_id, client_id, expires_at) \
                 SELECT $2, $3, oauth_identity_id, client_id, $4 FROM revoked \
              RETURNING id, oauth_identity_id, client_id \
             ) \
             SELECT id, oauth_identity_id, client_id FROM inserted",
        )
        .bind(old_hash)
        .bind(new_id)
        .bind(new_hash)
        .bind(new_expires_at)
        .fetch_optional(&self.pool)
        .await?;

        if let Some(row) = rotated {
            return Ok(Ok(RotatedRefreshToken {
                id: row.try_get("id")?,
                oauth_identity_id: row.try_get("oauth_identity_id")?,
                client_id: row.try_get("client_id")?,
            }));
        }

        // The conditional rotation matched nothing: find out why. A plain
        // lookup here is fine — this only runs on the already-wrong path
        // (unknown, expired, or reused token), never on a successful
        // redemption's hot path.
        let existing = sqlx_core::query::query(
            "SELECT revoked_at, expires_at, oauth_identity_id, client_id \
               FROM oauth_refresh_tokens WHERE hash = $1",
        )
        .bind(old_hash)
        .fetch_optional(&self.pool)
        .await?;

        let Some(existing) = existing else {
            return Ok(Err(RedeemRefreshTokenError::NotFound));
        };

        let revoked_at: Option<DateTime<Utc>> = existing.try_get("revoked_at")?;
        if revoked_at.is_some() {
            let oauth_identity_id: Uuid = existing.try_get("oauth_identity_id")?;
            let client_id: String = existing.try_get("client_id")?;
            self.revoke_refresh_tokens_for_identity_client(oauth_identity_id, &client_id)
                .await?;
            return Ok(Err(RedeemRefreshTokenError::Reused));
        }

        Ok(Err(RedeemRefreshTokenError::Expired))
    }

    /// Revoke every currently-active refresh token for one identity+client
    /// pair in a single statement. The reuse-detection response (see
    /// [`redeem_refresh_token`](Self::redeem_refresh_token)); also usable
    /// directly by a future "sign out this client" management action.
    pub async fn revoke_refresh_tokens_for_identity_client(
        &self,
        oauth_identity_id: Uuid,
        client_id: &str,
    ) -> Result<u64, StoreError> {
        let result = sqlx_core::query::query(
            "UPDATE oauth_refresh_tokens SET revoked_at = now() \
              WHERE oauth_identity_id = $1 AND client_id = $2 AND revoked_at IS NULL",
        )
        .bind(oauth_identity_id)
        .bind(client_id)
        .execute(&self.pool)
        .await?;
        Ok(result.rows_affected())
    }

    /// Revoke every currently-active refresh token for one identity, across
    /// *every* client — broader than
    /// [`revoke_refresh_tokens_for_identity_client`](Self::revoke_refresh_tokens_for_identity_client),
    /// which is scoped to a single client's reuse-detection blast radius.
    /// Leaves the identity bound. Unbinding uses
    /// [`delete_identity`](Self::delete_identity) to remove these rows and
    /// invalidate the identity's other credentials in the same transaction.
    pub async fn revoke_refresh_tokens_for_identity(
        &self,
        oauth_identity_id: Uuid,
    ) -> Result<u64, StoreError> {
        let result = sqlx_core::query::query(
            "UPDATE oauth_refresh_tokens SET revoked_at = now() \
              WHERE oauth_identity_id = $1 AND revoked_at IS NULL",
        )
        .bind(oauth_identity_id)
        .execute(&self.pool)
        .await?;
        Ok(result.rows_affected())
    }

    /// Delete rows that are done mattering to reuse detection: revoked more
    /// than [`SWEEP_WINDOW`] ago, or (for a row that timed out unredeemed,
    /// never revoked) expired more than [`SWEEP_WINDOW`] ago. Keeps
    /// [`issue_refresh_token`](Self::issue_refresh_token) and
    /// [`redeem_refresh_token`](Self::redeem_refresh_token)'s opportunistic
    /// sweeps from growing this table without bound — mirrors
    /// [`delete_expired_authorization_requests`](crate::Store::delete_expired_authorization_requests),
    /// except keyed off "long dead" rather than "past its own `expires_at`",
    /// since a *live* row's `revoked_at` is still `NULL` and its `expires_at`
    /// is exactly the reuse-detection horizon this sweep must not shorten.
    pub async fn delete_stale_refresh_tokens(&self) -> Result<u64, StoreError> {
        let cutoff = Utc::now() - SWEEP_WINDOW;
        let result = sqlx_core::query::query(
            "DELETE FROM oauth_refresh_tokens \
              WHERE (revoked_at IS NOT NULL AND revoked_at < $1) \
                 OR (revoked_at IS NULL AND expires_at < $1)",
        )
        .bind(cutoff)
        .execute(&self.pool)
        .await?;
        Ok(result.rows_affected())
    }
}
